### ISSUE TITLE
Unable to run the log4j tests

### ISSUE THREAD

**Issue by ashishkaran** [reportportal/example-java-TestNG#15]
Steps Followed:
1. Git clone
2. cd to log4j directory and mvn clean install

java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonInclude$Value.merge(Lcom/fasterxml/jackson/annotation/JsonInclude$Value;Lcom/fasterxml/jackson/annotation/JsonInclude$Value;)Lcom/fasterxml/jackson/annotation/JsonInclude$Value;
	at com.fasterxml.jackson.databind.ser.PropertyBuilder.<init>(PropertyBuilder.java:64)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructPropertyBuilder(BeanSerializerFactory.java:541)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:592)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:399)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:282)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:234)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:168)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1308)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1258)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:500)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:698)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:270)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3081)
	at com.epam.restendpoint.serializer.json.JacksonSerializer.serialize(JacksonSerializer.java:31)
	at com.epam.restendpoint.http.HttpClientRestEndpoint.executeRequest(HttpClientRestEndpoint.java:417)
	at com.epam.restendpoint.http.proxy.RestEndpointInvocationHandler.executeRestMethod(RestEndpointInvocationHandler.java:47)
	at com.epam.restendpoint.http.proxy.RestEndpointInvocationHandler.invoke(RestEndpointInvocationHandler.java:35)
	at com.sun.proxy.$Proxy21.startLaunch(Unknown Source)
	at com.epam.reportportal.service.ReportPortal.startLaunch(ReportPortal.java:118)
	at com.epam.reportportal.service.ReportPortal.startLaunch(ReportPortal.java:107)
	at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:87)
	at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:74)
	at org.testng.TestNG.runExecutionListeners(TestNG.java:1040)
	at org.testng.TestNG.run(TestNG.java:991)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by naeem-github** [comment]
maybe issue related dependency issue, I'm able to run the
`
C:\Users\myuser\git\example-java-TestNG\log4j>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building example-java-TestNG-log4j 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ example-java-TestNG-log4j ---
[INFO] Deleting C:\Users\myuser\git\example-java-TestNG\log4j\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example-java-TestNG-log4j ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 13 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ example-java-TestNG-log4j ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 8 source files to C:\Users\myuser\git\example-java-TestNG\log4j\target\classes
[WARNING] /C:/Users/myuser/git/example-java-TestNG/log4j/src/main/java/com/epam/rp/tests/Runner.java: C:\Users\myuser\git\example-java-TestNG\log4j\src\main\java\com\epam\rp\tests\Runner.java uses or overrides a deprecated API.
[WARNING] /C:/Users/myuser/git/example-java-TestNG/log4j/src/main/java/com/epam/rp/tests/Runner.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ example-java-TestNG-log4j ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\myuser\git\example-java-TestNG\log4j\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ example-java-TestNG-log4j ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ example-java-TestNG-log4j ---
[INFO] No tests to run.
[INFO] Surefire report directory: C:\Users\myuser\git\example-java-TestNG\log4j\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [com.epam.reportportal.apache] additivity to [true].
log4j: Level value for com.epam.reportportal.apache is  [OFF].
log4j: com.epam.reportportal.apache level set to OFF
log4j: Level value for root is  [info].
log4j: root level set to INFO
log4j: Class name: [com.epam.ta.reportportal.log4j.appender.ReportPortalAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n].
log4j: Adding appender named [ReportPortalAppender] to category [root].
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.516 sec - in TestSuite

Results :

Tests run: 14, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ example-java-TestNG-log4j ---
[INFO] Building jar: C:\Users\myuser\git\example-java-TestNG\log4j\target\example-java-TestNG-log4j-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ example-java-TestNG-log4j ---
[INFO] Installing C:\Users\myuser\git\example-java-TestNG\log4j\target\example-java-TestNG-log4j-1.0-SNAPSHOT.jar to C:\Users\myuser\.m2\repository\com\epam\rp\example-java-TestNG-log4j\1.0-SNAPSHOT\example-java-TestNG-log4j-1.0-SNAPSHOT.jar
[INFO] Installing C:\Users\myuser\git\example-java-TestNG\log4j\pom.xml to C:\Users\myuser\.m2\repository\com\epam\rp\example-java-TestNG-log4j\1.0-SNAPSHOT\example-java-TestNG-log4j-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.154 s
[INFO] Finished at: 2019-06-20T14:52:57+05:30
[INFO] Final Memory: 18M/189M
[INFO] ------------------------------------------------------------------------

C:\Users\myuser\git\example-java-TestNG\log4j>`
