### ISSUE TITLE
Reportportal client cannot build

### ISSUE THREAD

**Issue by KunalShokeen432** [reportportal/example-java-TestNG#18]
Hi All,

I have just setup reportPortal and able to access it on localhost.
After integrating it with my project using the steps metioned in this repo ,when I run the tests receiving below exception :

reportportal.properties contains details of 'new' created user for my project on RP 👍 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:254)
	at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:78)
	at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:73)
	at com.epam.reportportal.testng.TestNGService$MemoizingSupplier.get(TestNGService.java:541)
	at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:92)
	at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:57)
	at org.testng.TestRunner.addListener(TestRunner.java:1483)
	at org.testng.TestRunner.initListeners(TestRunner.java:347)
	at org.testng.TestRunner.init(TestRunner.java:255)
	at org.testng.TestRunner.init(TestRunner.java:222)
	at org.testng.TestRunner.<init>(TestRunner.java:171)
	at org.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:28)
	at org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_10.java:61)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:604)
	at org.testng.SuiteRunner.init(SuiteRunner.java:170)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1359)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1346)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:269)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
	... 23 more
Caused by: java.net.MalformedURLException
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:300)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:262)
	... 24 more
Caused by: java.lang.NullPointerException
	... 29 more

Something i am missing please help...

**Comment by KunalShokeen432** [comment]
This is now resolved.

**Comment by cam-sam1715** [comment]
> This is now resolved.

can you explain how you resolved
