### ISSUE TITLE
Cannot build reportportal client 

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/example-java-TestNG#25]
Running TestSuite
14:58:07.643 [main] ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client
java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:644)
	at java.net.URL.<init>(URL.java:507)
	at java.net.URL.<init>(URL.java:456)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:300)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:262)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
	at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:78)
	at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:73)
	at com.epam.reportportal.testng.TestNGService$MemoizingSupplier.get(TestNGService.java:541)
	at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:92)
	at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:57)
	at org.testng.TestNG.runExecutionListeners(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NullPointerException: null
	at java.net.URL.<init>(URL.java:549)
	... 18 common frames omitted
14:58:07.648 [main] ERROR com.epam.reportportal.service.ReportPortal - Cannot build ReportPortal client
com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:269)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
	at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:78)
	at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:73)
	at com.epam.reportportal.testng.TestNGService$MemoizingSupplier.get(TestNGService.java:541)
	at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:92)
	at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:57)
	at org.testng.TestNG.runExecutionListeners(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:644)
	at java.net.URL.<init>(URL.java:507)
	at java.net.URL.<init>(URL.java:456)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:300)
	at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:262)
	... 14 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.net.URL.<init>(URL.java:549)
	... 18 common frames omitted

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.922 s
[INFO] Finished at: 2019-12-17T14:58:08+05:30
[INFO] Final Memory: 14M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project maven_demo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
[ERROR] at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:254)
[ERROR] at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:78)
[ERROR] at com.epam.reportportal.testng.TestNGService$1.get(TestNGService.java:73)
[ERROR] at com.epam.reportportal.testng.TestNGService$MemoizingSupplier.get(TestNGService.java:541)
[ERROR] at com.epam.reportportal.testng.TestNGService.startLaunch(TestNGService.java:92)
[ERROR] at com.epam.reportportal.testng.BaseTestNGListener.onExecutionStart(BaseTestNGListener.java:57)
[ERROR] at org.testng.TestNG.runExecutionListeners(TestNG.java:1110)
[ERROR] at org.testng.TestNG.run(TestNG.java:1048)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
[ERROR] at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:269)
[ERROR] at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:250)
[ERROR] ... 13 more
[ERROR] Caused by: java.net.MalformedURLException
[ERROR] at java.net.URL.<init>(URL.java:644)
[ERROR] at java.net.URL.<init>(URL.java:507)
[ERROR] at java.net.URL.<init>(URL.java:456)
[ERROR] at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:300)
[ERROR] at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:262)
[ERROR] ... 14 more
[ERROR] Caused by: java.lang.NullPointerException
[ERROR] at java.net.URL.<init>(URL.java:549)
[ERROR] ... 18 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by dharma-keyutech** [comment]
This is pom.xml in my project




 	</properties>
	<repositories>
     <repository>
        <snapshots>
          <enabled>false</enabled>
        </snapshots>
        <id>bintray-epam-reportportal</id>
        <name>bintray</name>
        <url>http://dl.bintray.com/epam/reportportal</url>
     </repository>
</repositories>

	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.15</version>
		</dependency>
		
		  <dependency>
    		<groupId>org.apache.httpcomponents</groupId>
   			 <artifactId>httpclient</artifactId>
    		<version>4.5</version>
		</dependency>  
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-htmlunit-driver</artifactId>
			<version>2.21.0</version>
		</dependency>
		<dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		</dependency>
	<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
    <version>1.11.516</version>
</dependency>
<dependency>
<groupId>com.epam.reportportal</groupId>
  <artifactId>agent-java-testng</artifactId>
  <version>4.2.1</version>
</dependency>
<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>logger-java-logback</artifactId>
  <version>3.0.0</version>
</dependency>
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.3</version>
</dependency>
<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>logger-java-log4j</artifactId>
  <version>3.0.0</version>
</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>

					<suiteXmlFiles>
						<suiteXmlFile>demo_Maven.xml</suiteXmlFile> 
						
						
						
					</suiteXmlFiles>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by dharma-keyutech** [comment]
here is my pom.xml file
[pom_xml.txt](https://github.com/reportportal/example-java-TestNG/files/3972550/pom_xml.txt)

**Comment by evjlobanova** [comment]
@dharma-keyutech Could you please check our latest repository with all examples https://github.com/reportportal/examples-java

@Yumfriez could you please help

**Comment by avarabyeu** [comment]
URL to server is not provided. Please, make sure reportportal.properties is available in the root of classpath of your project

**Comment by dharma-keyutech** [comment]
Here is the URL To server that i Provided



![Capture](https://user-images.githubusercontent.com/58975085/71171006-bcfcd300-2282-11ea-94c7-f410c7a31174.PNG)

**Comment by dharma-keyutech** [comment]
Here Is my  project Structure


![Project Structure](https://user-images.githubusercontent.com/58975085/71171137-1402a800-2283-11ea-91fa-aae86c5cb27d.PNG)

**Comment by HardNorth** [comment]
@avarabyeu @evjlobanova @DzmitryHumianiuk Do we actually need that repo? I thought it's pretty outdated.

**Comment by DzmitryHumianiuk** [comment]
@HardNorth i guess - NO.
since we have https://github.com/reportportal/examples-java

**Comment by dharma-keyutech** [comment]
Getting an error in POM.XML


![error](https://user-images.githubusercontent.com/58975085/71477577-cb159b00-2810-11ea-8669-1f2135ad91e6.PNG)

Missing artifact com.epam.reportportal:logger-java-log4j:jar:5.0.0-BETA-2


Missing artifact com.epam.reportportal:logger-java-log4j:jar:5.0.0-BETA-2

**Comment by DzmitryHumianiuk** [comment]
@dharma-keyutech https://github.com/reportportal/examples-java/tree/master/example-testng-logback try this

**Comment by dharma-keyutech** [comment]
![example-testng-logback](https://user-images.githubusercontent.com/58975085/71558296-863f6d80-2a77-11ea-8a15-dadd81d6884e.png)



Getting Error in POM.XML
